services:
  app:
    image: bbbingyan:latest //替换自己构建的镜像
    ports:
      - "714:714"
    depends_on:
      - db
  db:
    image: postgres:15.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres..
      POSTGRES_DB: bbbingyan
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq..
    ports:
      - "5672:5672"
      - "15672:15672"