server:
  port: 714
  # http://localhost:714
  host: "http://oorangeeee.com"
database:
  dataBaseUserName: "postgres"
  dataBasePassword: "bsbflsgxh.."
  # 127.0.0.1
  dataBaseIp: "db"
  dataBasePort: "5432"
  dataBaseName: "bbbingyan"
CSRF:
  cookieSecure: false
  cookieHTTPOnly: true
  cookieMaxAge: 7200
email:
  emailHost: "smtp.163.com"
  emailPort: 465
  emailUserName: "Jin0714ForProject@163.com"
  emailPassword: "ZYEAXFBDERNHYQNF"
  emailFromNickname: "BBBingyan团队"
  emailOfFollow:
    subject: "BBBingyan关注的人发布新文章了！(Follow Notification)"
    body: |
      <!DOCTYPE html>
      <html lang="zh">
      <head>
          <meta charset="UTF-8">
          <title>关注的人发布新文章通知</title>
      </head>
      <body>
          <p>亲爱的 {用户名},</p>
          <p>您好！</p>
          <p>您关注的人发布了新文章。</p>
          <p>文章标题：{文章标题}</p>
          <p>请您点击下面的链接查看详情：</p>
          <p><a href="文章链接">http://localhost:714/passage/{passage-id}</a></p>
          <p>如果您有任何疑问或需要帮助，请随时回复此邮件或联系我们的客户支持团队。</p>
          <p>祝好，</p>
          <p>BBBingyan团队</p>
          <p>联系电话：{联系电话}</p>
          <p>电子邮箱：{电子邮件地址}</p>
          <p>官方网站：<a href="{官方网站}">{官方网站}</a></p>
      </body>
      </html>
  emailOfAt:
    subject: "BBBingyan@提到通知(Mention Notification)"
    body: |
      <!DOCTYPE html>
      <html lang="zh">
      <head>
          <meta charset="UTF-8">
          <title>提到通知</title>
      </head>
      <body>
          <p>亲爱的 {用户名},</p>
          <p>您好！</p>
          <p>您在BBBingyan服务中被提到了。</p>
          <p>提到您的内容如下：</p>
          <p><a href="文章链接">http://localhost:714/passage/{passage-id}</a></p>
          <p>请您点击上述链接查看详情。</p>
          <p>如果您有任何疑问或需要帮助，请随时回复此邮件或联系我们的客户支持团队。</p>
          <p>祝好，</p>
          <p>BBBingyan团队</p>
          <p>联系电话：{联系电话}</p>
          <p>电子邮箱：{电子邮件地址}</p>
          <p>官方网站：<a href="{官方网站}">{官方网站}</a></p>
      </body>
      </html>
  emailOfLogin:
    timeRange: 5
    subject: "BBBingyan登录通知(Login Notification)"
    body: |
      <!DOCTYPE html>
      <html lang="zh">
      <head>
          <meta charset="UTF-8">
          <title>登录通知</title>
      </head>
      <body>
          <p>亲爱的 {用户名},</p>
          <p>您好！</p>
          <p>您的账户于 {登录时间} 登录了BBBingyan服务。</p>
          <p>如果这是您本人的操作，登录验证码为：{验证码}。</p>
          <p>如果这不是您本人的操作，请立即修改您的密码以保护您的账户安全。</p>
          <p>如果您有任何疑问或需要帮助，请随时回复此邮件或联系我们的客户支持团队。</p>
          <p>祝好，</p>
          <p>BBBingyan团队</p>
          <p>联系电话：{联系电话}</p>
          <p>电子邮箱：{电子邮件地址}</p>
          <p>官方网站：<a href="{官方网站}">{官方网站}</a></p>
      </body>
      </html>
  emailOfRegister:
    timeRange: 5
    subject: "欢迎使用BBBingyan(Welcome to BBBingyan)"
    body: |
      <!DOCTYPE html>
      <html lang="zh">
      <head>
          <meta charset="UTF-8">
          <title>激活您的账户</title>
      </head>
      <body>
          <p>亲爱的 {用户名},</p>
          <p>您好！</p>
          <p>感谢您注册BBBingyan服务。为了确保您的账户能够顺利使用我们的服务，我们需要您完成账户激活步骤。</p>
          <p>请通过点击下面的激活链接来激活您的账户：</p>
          <p><a href="{激活链接}">点击此处激活您的账户</a></p>
          <p>如果在点击链接时遇到任何问题，您可以将以下链接复制并粘贴到您的网络浏览器地址栏中：</p>
          <p>{激活链接}</p>
          <p>完成激活后，您将能够立即开始使用我们的服务。</p>
          <p>如果您有任何疑问或需要帮助，请随时回复此邮件或联系我们的客户支持团队。</p>
          <p>欢迎加入BBBingyan大家庭，我们期待为您提供卓越的服务体验。</p>
          <p>祝好，</p>
          <p>BBBingyan团队</p>
          <p>联系电话：{联系电话}</p>
          <p>电子邮箱：{电子邮件地址}</p>
          <p>官方网站：<a href="{官方网站}">{官方网站}</a></p>
      </body>
      </html>
info:
  contactPhone: "13389791067"
  emailAddress: "Jin0714ForProject@163.com"
  webSite: "http://oorangeeee.com"
jwt:
  jwtSecret: "w2qrS8mXMLbCCsw9HfMBwxyCZFVEYgyVzSFP6QJsXVNd0T9003lzKX8tDxNk25l9GO2wqiIYcWVsj5RXpQ3jHYxjH9riPkKWA4NBv1Kz2rFyIPMjL5brKZk9xGpiAhXQzBAwhJWMsEb7cE2Tfg4LZpMmtWFkb3uPAcC20V9IS5EUhnTclLSQa6pFjsQ9nS0XkM8YBI7O2VuEszmyLr7nT8N7WJwyYSYbJGYtbjZZfj5EQn38"
passage:
  tags: "求助,分享,讨论,建议,公告,恋爱,生活,学习,技术,创作,其他"
admin:
  adminSecret: "9wyQKeF06StmYgrAmzTJlOvo21GneUHs"
rabbitmq:
  url: "amqp://rabbitmq:bsbflsgxh..@rabbitmq:5672/"

