server:
  port: 714
  host: "http://localhost:714"
database:
  dataBaseUserName: "postgres"
  dataBasePassword: "bsbflsgxh.."
  dataBaseIp: "127.0.0.1"
  dataBasePort: "5432"
  dataBaseName: "sep"
CSRF:
  cookieSecure: false
email:
  emailHost: "smtp.163.com"
  emailPort: 465
  emailUserName: "Jin0714ForProject@163.com"
  emailPassword: "ZYEAXFBDERNHYQNF"
  emailFromNickname: "肠镜明眸官方团队"
  emailOfRegister:
    timeRange: 5
    subject: "欢迎使用肠镜明眸(Welcome to Sagacious Eye for Polyp)"
    body: |
      <!DOCTYPE html>
      <html lang="zh">
      <head>
          <meta charset="UTF-8">
          <title>激活您的账户</title>
      </head>
      <body>
          <p>亲爱的 {用户名},</p>
          <p>您好！</p>
          <p>感谢您注册肠镜明眸 (Sagacious Eye for Polyp) 服务。为了确保您的账户能够顺利使用我们的服务，我们需要您完成账户激活步骤。</p>
          <p>请通过点击下面的激活链接来激活您的账户：</p>
          <p><a href="{激活链接}">点击此处激活您的账户</a></p>
          <p>如果在点击链接时遇到任何问题，您可以将以下链接复制并粘贴到您的网络浏览器地址栏中：</p>
          <p>{激活链接}</p>
          <p>完成激活后，您将能够立即开始使用我们的服务，享受更清晰的肠道健康监测体验。</p>
          <p>如果您有任何疑问或需要帮助，请随时回复此邮件或联系我们的客户支持团队。</p>
          <p>欢迎加入肠镜明眸 (Sagacious Eye for Polyp) 大家庭，我们期待为您提供卓越的服务体验。</p>
          <p>祝好，</p>
          <p>肠镜明眸 (Sagacious Eye for Polyp) 团队</p>
          <p>联系电话：{联系电话}</p>
          <p>电子邮箱：{电子邮件地址}</p>
          <p>官方网站：<a href="{官方网站}">{官方网站}</a></p>
      </body>
      </html>
info:
  contactPhone: "123456789"
  emailAddress: "Jin0714ForProject@163.com"
  webSite: "http://localhost:714"
